import type { PermissionCode } from "@/shared/types/PermissionTypes";

export const PERMISSION_GROUPS: Record<string, PermissionCode[]> = {
  USUARIOS: [
    "USER_VIEW",
    "USER_CREATE",
    "USER_UPDATE",
    "USER_DELETE",
    "USER_ROLE_ASSIGN",
    "USER_ROLE_REMOVE",
    "USER_TOGGLE_STATUS",
    "USER_IMPORT",
    "USER_EXPORT",
    "USER_EXPORT_ALL",
    "USER_PROFILE_UPDATE",
    "USER_PROFILE_DELETE",
  ],
  ROLES: [
    "ROLE_VIEW",
    "ROLE_CREATE",
    "ROLE_UPDATE",
    "ROLE_DELETE",
    "ROLE_PERMISSION_UPDATE",
    "ROLE_PERMISSION_ADD",
    "ROLE_PERMISSION_REMOVE",
  ],
  PROYECTOS: [
    "PROJECT_CREATE",
    "PROJECT_VIEW",
    "PROJECT_VIEW_ALL",
    "PROJECT_VIEW_MINE",
    "PROJECT_UPDATE",
    "PROJECT_ASSIGN_CURATOR",
    "PROJECT_ADD_OBSERVATIONS",
    "PROJECT_APPROVE",
    "PROJECT_VIEW_ASSIGNED",
    "PROJECT_DELETE",
    "PROJECT_VIEW_READY_TO_PUBLISH",
  ],
  AUDITORIA: ["AUDIT_VIEW", "AUDIT_DETAIL_VIEW"],
  CIUDADANIA: ["CITIZEN_ACTION_CREATE", "CITIZEN_ACTION_VIEW"],
};

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  USER_VIEW: "Ver usuarios",
  USER_CREATE: "Crear usuario",
  USER_UPDATE: "Actualizar usuario",
  USER_DELETE: "Eliminar usuario",
  USER_ROLE_ASSIGN: "Asignar roles a usuario",
  USER_ROLE_REMOVE: "Remover roles de usuario",
  USER_TOGGLE_STATUS: "Activar o desactivar usuario",
  USER_IMPORT: "Importar usuarios",
  USER_EXPORT: "Exportar usuarios",
  USER_EXPORT_ALL: "Exportar todos los usuarios",
  USER_PROFILE_UPDATE: "Actualizar perfil propio",
  USER_PROFILE_DELETE: "Eliminar cuenta propia",

  ROLE_VIEW: "Ver roles",
  ROLE_CREATE: "Crear rol",
  ROLE_UPDATE: "Actualizar rol",
  ROLE_DELETE: "Eliminar rol",
  ROLE_PERMISSION_UPDATE: "Actualizar permisos del rol",
  ROLE_PERMISSION_ADD: "Agregar permiso al rol",
  ROLE_PERMISSION_REMOVE: "Remover permiso del rol",

  PROJECT_CREATE: "Crear proyecto",
  PROJECT_VIEW: "Ver proyectos",
  PROJECT_VIEW_ALL: "Ver todos los proyectos",
  PROJECT_VIEW_MINE: "Ver mis proyectos",
  PROJECT_UPDATE: "Actualizar proyecto",
  PROJECT_ASSIGN_CURATOR: "Asignar curador",
  PROJECT_ADD_OBSERVATIONS: "Agregar observaciones",
  PROJECT_APPROVE: "Aprobar proyecto",
  PROJECT_VIEW_ASSIGNED: "Ver proyectos asignados",
  PROJECT_DELETE: "Eliminar proyecto",
  PROJECT_VIEW_READY_TO_PUBLISH: "Ver proyectos listos para publicar",

  AUDIT_VIEW: "Ver auditoría",
  AUDIT_DETAIL_VIEW: "Ver detalles de auditoría",

  CITIZEN_ACTION_CREATE: "Crear acción ciudadana",
  CITIZEN_ACTION_VIEW: "Ver acciones ciudadanas",
};
